### ISSUE TITLE
文档建设需求

### ISSUE THREAD

**Issue by rocky-zh** [NetEase/tango#1]
1. 架构体系设计说明
2. 很多代码中文注释不全
3. 低代码开发文档
4. 二次开发扩展手册
5. 路线图

**Comment by wwsun** [comment]
正在完善中，下周开始会逐步开始更新。

**Comment by juukee** [comment]
我demo没跑起来....

**Comment by wwsun** [comment]
请参考文档跑 demo 哟，本地运行还需要运行沙箱服务。https://netease.github.io/tango/docs/designer/quick-start

**Comment by juukee** [comment]
本地沙箱环境没跑起来，尴尬

**Comment by Johnjiang2016** [comment]
组件联动，属性支持表达式，事件，这块是怎么设计的，文档能简单的说明下吗
