### ISSUE TITLE
可以支持更换 react 项目框架么？

### ISSUE THREAD

**Issue by MisterBoole** [NetEase/tango#102]
[tango-boot](https://github.com/NetEase/tango-boot) 虽然已经是比较好的实现， 可针对已经搭建好的其他项目框架(例如 umi4), 还是不太好支持

**Comment by wwsun** [comment]
因为搭建过程需要对源码进行操纵修改，所以引擎内部预置了一些状态操纵逻辑，tango-boot 目前为引擎的实现提供了一套标准的方案。其他状态管理库或框架，涉及到额外的代码生成和修改问题，需要面向特定的场景单独扩展（实现额外的 core 包即可），不适合在引擎内部实现。
