### ISSUE TITLE
有没有交流群啊

### ISSUE THREAD

**Issue by yangfeng123** [NetEase/tango#106]
有没有微信，或者qq交流群呀，非常看好这个模式

**Comment by wangminqinag** [comment]
是的能否创建 qq 或者 微信的交流群

**Comment by SkyWongHZ** [comment]
<img width="707" alt="image" src="https://github.com/NetEase/tango/assets/20575355/1e61f0a5-7df8-49dc-b31a-67e75c312a66">
项目跑起来后压根打不开啊

**Comment by yangfeng123** [comment]
能打开，就是还需要按照沙箱才能加载设计器

**Comment by FKLam** [comment]
是的吖，希望开个交流群，那样方便些，谢谢。

**Comment by wwsun** [comment]
目前可以讨论组进行交流 https://github.com/NetEase/tango/discussions
