### ISSUE TITLE
能否提供一个 vitesandbox-client   类似 www 的产物

### ISSUE THREAD

**Issue by wangminqinag** [NetEase/tango#109]
能否提供一个 https://mcuking.github.io/vitesandbox-client/ 这个地址部署的 html 文件 @ccloli

**Comment by ccloli** [comment]
你可以尝试从 [原仓库](https://github.com/mcuking/vitesandbox-client) 手动构建获取产物。

不过我们已经废弃了该方案，所以这套沙箱方案已经不在 Tango 体系的范围内。而且该沙箱的 api 与 Tango 目前使用的 CodeSandbox 方案不是完全兼容的，所以不一定能直接使用。

**Comment by wangminqinag** [comment]
@ccloli  @wwsun 我就是想用codesandbox-client 实现vue 的热更新咋就这么难嘞， 现在准备看codesandbox-client 的源码， 我看社区好多人想要有 讨论群， 为什么没有响应呢， 有些问题问你们可能没有时间精力去分析， 创建一些群让大家讨论一下啊

**Comment by wwsun** [comment]
> @ccloli @wwsun 我就是想用codesandbox-client 实现vue 的热更新咋就这么难嘞， 现在准备看codesandbox-client 的源码， 我看社区好多人想要有 讨论群， 为什么没有响应呢， 有些问题问你们可能没有时间精力去分析， 创建一些群让大家讨论一下啊

可以查看：https://github.com/NetEase/tango/discussions/7
