### ISSUE TITLE
在windows WSL环境中启动tango和本地沙箱时失败

### ISSUE THREAD

**Issue by maxwls** [NetEase/tango#113]
参考tango文档【[快速开始](https://netease.github.io/tango-site/docs/designer/quick-start/)】在WSL环境中运行tango和codesandbox。
### 启动本地沙箱
1. 修改Caddyfile
![image](https://github.com/NetEase/tango/assets/4974265/c25f0b4f-cc13-451d-8e31-7e0ceeb3f278)

2. 本地build成功
![image](https://github.com/NetEase/tango/assets/4974265/1bd8ec8f-c9ad-48d8-9582-9fae94efcca3)

3. 查看wsl ip
![image](https://github.com/NetEase/tango/assets/4974265/96ace642-fe08-4c39-88b0-8cb9f856ea30)
 
4. 修改/etc/hosts文件
![image](https://github.com/NetEase/tango/assets/4974265/92868159-1fb1-490b-ad67-b78c55cbbcbb)

5. 启动caddy 
![image](https://github.com/NetEase/tango/assets/4974265/30dc1c3f-17ec-443a-baed-89caebb7b941)

###  运行tango
1. 修改 apps/playground/src/pages/index.tsx
![image](https://github.com/NetEase/tango/assets/4974265/82ca094a-2eb3-49d7-b37f-1f35a43d6ea0)

2. 修改C:\Windows\System32\drivers\etc\hosts
![image](https://github.com/NetEase/tango/assets/4974265/700b8829-51a8-41e3-a4c6-1bb803ba67a3)

3. start tango
![image](https://github.com/NetEase/tango/assets/4974265/f54d9c83-fd0b-42d6-a678-6025fb6ef20f)

### windows防火墙关闭
![image](https://github.com/NetEase/tango/assets/4974265/88d5399a-61ce-4009-b675-86385d17544c)

### wsl防火墙关闭
![image](https://github.com/NetEase/tango/assets/4974265/e6ee280c-0982-4936-b31a-35d80a43d822)

### 访问tango
![image](https://github.com/NetEase/tango/assets/4974265/9a4d6704-2d69-49d7-b93e-3e55a07d57d3)

**Comment by ccloli** [comment]
看起来是 WSL2？如果是 WSL1 的话理论上是可行的，直接使用 127.0.0.1 即可

WSL2 是虚拟化的，可能需要做路由转发或是桥接？建议先尝试在 WSL2 子系统里启动一个简单的 HTTP 服务器（例如 `npx http-server -p 8080` 或者 `python -m http.server 8080`），确认是否能直接访问，或者尝试 `wsl -t` 终止子系统再重新启动试试看

至于问题的具体排查，可能就需要折腾系统配置了，大概率和项目本身没太大关系 😂

**Comment by maxwls** [comment]
关掉clash后，可以打开了。

**Comment by maxwls** [comment]
关掉clash后，可以打开了。
