### ISSUE TITLE
Table组件的TableColumn要怎么选中呢

### ISSUE THREAD

**Issue by iamxiao01** [NetEase/tango#123]
![image](https://github.com/NetEase/tango/assets/48314121/ca92dbbf-a416-4b08-8f95-f71c947d621e)
![image](https://github.com/NetEase/tango/assets/48314121/00cd88b8-bf9d-49a9-bba8-f38b45a93afa)

**Comment by iamxiao01** [comment]
因为Table.Column组件返回是null，所以需要创建一个占位框来模拟Column的占位，然后点击这个模板来设置Column的属性，麻烦问下作者，你们内部使用是这样的实现的吗？
![image](https://github.com/NetEase/tango/assets/48314121/98f0ce87-a452-4fd2-8450-729976b5156c)
![image](https://github.com/NetEase/tango/assets/48314121/2cbffaac-1d7f-4e36-a107-8ec596f23883)

**Comment by wwsun** [comment]
可以用 columnSetter

**Comment by wangminqinag** [comment]
@iamxiao01  为啥我拉下来代码 没有看到 table 的物料呢

**Comment by iamxiao01** [comment]
自己搞组件打包发布，替换mack-files里的资源

**Comment by Tkzc0811** [comment]
使用columnSetter,如何设置操作列？希望添加按钮增加点击事件
