### ISSUE TITLE
执行 yarn start，启动不了项目

### ISSUE THREAD

**Issue by ljxok2001** [NetEase/tango#14]
MacOS 之下启动，遇到下面的提示

```shell
yarn run v1.22.19
$ yarn workspace playground start
$ HTTPS=1 umi dev
Starting the development server...

● Webpack █████████████████████████ building (10%) 1/2 modules 1 active
 babel-loader › src/.umi/umi.ts

(node:24976) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND local.netease.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Emitted 'error' event on Server instance at:
    at Server.emit (/Users/www/node_modules/@umijs/deps/compiled/spdy/spdy.js:1:211183)
    at GetAddrInfoReqWrap.doListen (node:net:2066:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'local.netease.com'
}

Node.js v20.5.0
✨  Done in 3.20s.
```

**Comment by dongoa** [comment]
同一个问题

**Comment by dongoa** [comment]
yarn start 
yarn run v1.22.19
$ yarn workspace playground start
$ HTTPS=1 umi dev
Starting the development server...

● Webpack █████████████████████████ building (10%) 1/2 modules 1 active
 babel-loader › src/.umi/umi.ts

(node:31075) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND local.netease.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
Emitted 'error' event on Server instance at:
    at Server.emit (/Users/aodong/Documents/WORK/lowcodeTest/tango/node_modules/@umijs/deps/compiled/spdy/spdy.js:1:211183)
    at GetAddrInfoReqWrap.doListen (node:net:1657:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'local.netease.com'
}
✨  Done in 3.67s.

**Comment by wwsun** [comment]
端口冲突？或是使用 vpn ?

**Comment by ccloli** [comment]
请确认已参考 [文档](https://netease.github.io/tango/docs/designer/quick-start) 在 hosts 文件中（一般是 `/etc/hosts`）添加如下配置  
```hosts
127.0.0.1 local.netease.com
```

若修改后仍未生效，请确认是否是本地存在代理软件劫持了请求，导致无法使用 hosts 文件里的解析

**Comment by ljxok2001** [comment]
谢谢 @wwsun @OMGVecchio  @ccloli 的回复，按照指引 local.netease.com 这个域名我已经配置好，并可以在浏览器访问了，上面我提到的问题已经不存在，不过在执行 `yarn start` 的时候，又遇到了一个新的问题，导致启动不了：
```shell
sudo yarn start
yarn run v1.22.19
$ yarn workspace playground start
$ HTTPS=1 umi dev
Starting the development server...

● Webpack █████████████████████████ building (10%) 1/2 modules 1 active
 babel-loader › src/.umi/umi.ts

(node:78457) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports.__webpack_modules__.57442.module.exports (/Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:135907:62)
    at NormalModule._initBuildHash (/Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109317:16)
    at /Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109352:10
    at /Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109223:13
    at /Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61151:11
    at /Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61017:18
    at context.callback (/Users/www/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:60895:13)
    at /Users/www/node_modules/@umijs/deps/compiled/babel-loader/index.js:1:130029 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.0
✨  Done in 3.56s.
```

**Comment by ccloli** [comment]
> `Node.js v20.5.0`

这应该是 Node.js 17+ 从 OpenSSL 2.0 改为使用 OpenSSL 3.0，而当前脚手架使用的 webpack 版本使用了 OpenSSL 3.0 中废弃的方法导致的

https://github.com/webpack/webpack/issues/14532

请尝试降级至 Node.js 16 再启动试试看，或尝试使用以下指令在新版本 Node.js 下启动项目：

```sh
NODE_OPTIONS="--openssl-legacy-provider" yarn start
```

> `sudo yarn start`

另外项目启动应该不需要 sudo

**Comment by ljxok2001** [comment]
谢谢 @ccloli ，通过 `NODE_OPTIONS="--openssl-legacy-provider" yarn start` 成功启动了，很棒。

另外，提醒一下未来的朋友们，要关掉 vpn 或者在 vpn 客户端中忽略掉对 local.netease.com 的代理，不然访问不了。
