### ISSUE TITLE
iconSetter设置了以后不进行自动import吗

### ISSUE THREAD

**Issue by liyzy** [NetEase/tango#148]
iconSetter没有设置吗，用的expressionSetter，假如使用button组件，使用@ant-design/icons，添加了依赖以后，在icon中填写<SearchOutlined />，但是源码中不会自动import { SearchOutlined } from '@ant-design/icons';

**Comment by liyzy** [comment]
假如我在menuData中添加了RadioGroup，但会报错
![image](https://github.com/NetEase/tango/assets/168048243/18ebad95-5f1a-4ca5-847e-bf8417436d18)
![image](https://github.com/NetEase/tango/assets/168048243/27eb7a54-294a-4b42-b68d-13f65c2ca3de)

**Comment by wwsun** [comment]
组件包没有导出 RadioGroup 这个组件吧

**Comment by wwsun** [comment]
> iconSetter没有设置吗，用的expressionSetter，假如使用button组件，使用@ant-design/icons，添加了依赖以后，在icon中填写，但是源码中不会自动import { SearchOutlined } from '@ant-design/icons';

这个现在是 setter 的 onChange 逻辑里处理的。可以在 onChagne 的参数二里抛出 relatedImports 提供导入声明

https://github.com/NetEase/tango/blob/897fe0a5a1fb19c62d313d6ff957f497e6746890/packages/designer/src/setters/render-setter.tsx#L48

**Comment by liyzy** [comment]
> > iconSetter没有设置吗，用的expressionSetter，假如使用button组件，使用@ant-design/icons，添加了依赖以后，在icon中填写，但是源码中不会自动import { SearchOutlined } from '@ant-design/icons';
> 
> 这个现在是 setter 的 onChange 逻辑里处理的。可以在 onChagne 的参数二里抛出 relatedImports 提供导入声明
> 
> https://github.com/NetEase/tango/blob/897fe0a5a1fb19c62d313d6ff957f497e6746890/packages/designer/src/setters/render-setter.tsx#L48
但是relatedImports需要在组件属性配置中提前就声明好是吗，但是对于这种动态引入的，目前有可以自动导入吗

**Comment by liyzy** [comment]
![image](https://github.com/NetEase/tango/assets/168048243/739c0b01-190b-46d9-bd00-f8631b2eda0e)
像div这种，导入的作用是什么呀，可以当做组件用吗

**Comment by wwsun** [comment]
> ![image](https://private-user-images.githubusercontent.com/168048243/329744926-739c0b01-190b-46d9-bd00-f8631b2eda0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDQyOTMsIm5iZiI6MTcxNTQwMzk5MywicGF0aCI6Ii8xNjgwNDgyNDMvMzI5NzQ0OTI2LTczOWMwYjAxLTE5MGItNDZkOS1iZDAwLWY4NjMxYjJlZGEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNTA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDc4MTdlNGMwNDJkNGQzZTVlNGFjMWQ3NzVhYTU5ZmExMTE5YjE2NmRkZTRhNzI5MDI4MTVjZjJjMThjOTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZlpqTsC4NYbpIROVYtPv0AF9jgZiSujP6R3b6R456I) 像div这种，导入的作用是什么呀，可以当做组件用吗

新版支持了选种 html 节点进行配置
