### ISSUE TITLE
本地部署后“组件”加载不出来，一直转圈

### ISSUE THREAD

**Issue by A-afflatus** [NetEase/tango#16]
操作系统：mac 
tango、codesandbox-client都正常安装部署了，进入网页程序之后，组件一直加载不出来

**Comment by ccloli** [comment]
如果沙箱内的 demo 本身就无法正常加载，请确认是否能正常访问 unpkg 与 jsdelivr，以及是否信任了沙箱的自签证书

如果沙箱内的 demo 可以正常加载，这可能是无法访问沙箱内部的 `window` 导致的，请确认已按照 [文档](https://netease.github.io/tango/docs/designer/quick-start) 的流程操作，并修改了 `<Sandbox>` 的 `bundlerURL` 为本地的 sandbox 地址。文档内的 codesandbox 是使用 Caddy 启动的，`Caddyfile` 已经添加了允许在 Chrome 115+ 设置 `document.domain` 的 http 响应头

如果 codesandbox 不是通过 Caddy 启动的（如 nginx 等），请确认沙箱与设计器的请求返回的 HTTP 响应头均包含 `Origin-Agent-Cluster: ?0`

![image](https://github.com/NetEase/tango/assets/8115912/f2e611ac-d4fd-4c8f-a8c4-4561f8b92929)
