### ISSUE TITLE
这个项目没在做开源的支持了么？文档这些基本没有更新，也没有交流群

### ISSUE THREAD

**Issue by liangxp** [NetEase/tango#164]
如题

**Comment by wwsun** [comment]
1. 开源至今的 commit 频率
![image](https://github.com/NetEase/tango/assets/6984035/3f5c7611-afa1-4116-85f0-a46495eb2b04)

2. 文档目前已经更新了一个[完整版本](https://netease.github.io/tango-site/docs/designer/quick-start)，核心的细节都已经提供，并且已经上线了 [API 文档](https://netease.github.io/tango/index.html)

3. 交流群可以在 https://github.com/NetEase/tango/discussions 进行讨论
