### ISSUE TITLE
Nice try...

### ISSUE THREAD

**Issue by nwind** [NetEase/tango#17]
看起来更像是 JSX 界面设计器。

这种设计的问题是完全没法摆脱代码编辑，比如 

```javascript
let button;
if (isLoggedIn) {
  button = <Button children="按钮1" />;
} else {
  button = <Button children="按钮2" />;
}
return (
  <Page title="页面标题">
    <Section></Section>
    <Section>{button}</Section>
  </Page>
);
```

可视化编辑器永远看不到另一个了，必须切换到代码编辑模式

**Comment by millerhamburger** [comment]
> 写法的灵活性是永远无法预测的。因此，目前我们会配合 [TangoBoot](https://github.com/NetEase/tango-boot) 框架层提供搭建的最佳实践，可视化提供了一种新型的编程能力，但底层仍然需要依赖框架和组件提供能力封装，这部分后面我们会逐步放出我们内部的实践。
> 
> 例如逻辑可以变为
> 
> ```js
> <When test="case1">
>   <Button children="按钮1" />
> </When>
> ```

那不是又是一种新写法了。。。。
