### ISSUE TITLE
codesandbox-client 有办法支持 vite 吗

### ISSUE THREAD

**Issue by luoheix** [NetEase/tango#181]
1. codesandbox 有一个 [Vue 3 + Vite 的模板](https://github.com/codesandbox/codesandbox-template-vue)，我们有办法支持这个模板吗，或者有什么思路吗
2. 还想问一个，如何禁止 codesandbox 将 ESM 转译为 CommonJS，是要修改对应的 Babel 吗

**Comment by wwsun** [comment]
此需求可以咨询 https://github.com/codesandbox/codesandbox-client 或提 PR 哦
