### ISSUE TITLE
error An unexpected error occurred: "https://registry.npmjs.org/@music163/tango-boot/-/tango-boot-0.3.0.tgz: connect ETIMEDOUT 104.16.1.35:443".

### ISSUE THREAD

**Issue by GeeFib** [NetEase/tango#187]
yarn can not succeed
when I use yarn，it looks something wrong
error An unexpected error occurred: "https://registry.npmjs.org/@music163/tango-boot/-/tango-boot-0.3.0.tgz: connect ETIMEDOUT 104.16.1.35:443".

**Comment by ccloli** [comment]
Looks like it's a network issue, make sure your network connection is stable, and npmjs.org is not blocked by firewall or your ISP.

If you're in Mainland China, consider setting registry to `https://registry.npmmirror.com/`.
