### ISSUE TITLE
支持函数式组件吗?

### ISSUE THREAD

**Issue by eightHundreds** [NetEase/tango#19]
虽然能正常运行,但是根据源码和公开的ppt, 用的都是类组件

**Comment by wwsun** [comment]
可以使用，但我们推荐状态与视图分离，所以 函数组件 和 普通类组件 并没有太大差异。

**Comment by wwsun** [comment]
详见 Tango 低代码应用规范：https://netease.github.io/tango/docs/boot/app-spec
