### ISSUE TITLE
大佬这个可以生成vue2或者vue3源码么？

### ISSUE THREAD

**Issue by GavenXia** [NetEase/tango#2]

**Comment by wwsun** [comment]
目前只适配了 react 的 ast 解析和操纵逻辑。 vue 后续可以考虑社区共建下，逻辑上是一样的。

**Comment by Wyatex** [comment]
希望能支持下vue3

**Comment by wangminqinag** [comment]
> 目前只适配了 react 的 ast 解析和操纵逻辑。 vue 后续可以考虑社区共建下，逻辑上是一样的。

codesandbox-client 支持react 热更新， 不支持 vue 热更新  https://github.com/NetEase/tango/issues/101
