### ISSUE TITLE
using tango to build other framework

### ISSUE THREAD

**Issue by SOG-web** [NetEase/tango#200]
since sandpack supports other framework how do I use it for designing other e.g svelte, angular e.t.c

**Comment by wwsun** [comment]
Currently, Tango only supports the parsing and manipulation of the AST for javascript react. For other frameworks, the `tango/core/models/xxxModule` implementation needs to be extended accordingly.

**Comment by SOG-web** [comment]
> Currently, Tango only supports the parsing and manipulation of the AST for javascript react. For other frameworks, the `tango/core/models/xxxModule` implementation needs to be extended accordingly.

Can we get a simple complete example of how to use Tango without a designer? Maybe we want to implement the designer ourselves, or just want to be able to listen to mouse events, drag and drop events of the iframe.

The reason why I need this is that am trying to find a way to make it multi-framework, but am stuck at making use of the sandbox, if am able to get the mouse events from the sandbox, i could find a way to make it multi-framework

**Comment by SOG-web** [comment]
Have tried following this https://netease.github.io/tango-site/docs/designer/deploy/sandbox/ but it not working
