### ISSUE TITLE
控制模态框的显示与隐藏我看是调用的tango.openModal(id)，但是框架里并没有实现tango.openModal() 函数，想问下通过模态框id控制模态框显示与隐藏的逻辑是什么

### ISSUE THREAD

**Issue by zhanghaosysu** [NetEase/tango#208]
控制模态框的显示与隐藏我看是调用的tang.openModal(id)，但是框架里并没有实现tang.openModal() 函数，想问下通过模态框id控制模态框显示与隐藏的逻辑是什么

**Comment by wwsun** [comment]
可以在 Modal 实现里支持通过事件唤起关闭
