### ISSUE TITLE
pageStore的定义与使用

### ISSUE THREAD

**Issue by Tkzc0811** [NetEase/tango#212]
![image](https://github.com/user-attachments/assets/f2581970-5173-4e74-a2f6-219161e40acd)
看到例子中有使用pageStore。这个是在哪里定义呢？是和store一样嘛？

**Comment by Tkzc0811** [comment]
试了一下，全局是可以直接使用tango.pageStore这个变量的。但是在表单中如何使用呢

**Comment by wwsun** [comment]
pageStore 被用来自动收集页面中组件实例的内部状态，可以参考代码 https://github.com/NetEase/tango-boot/blob/main/packages/boot/src/defineComponent.tsx
