### ISSUE TITLE
新添加的组件选中不了

### ISSUE THREAD

**Issue by 1303106965** [NetEase/tango#216]
原因是组件缺少属性data-dnd，并且与demo的组件相比较还少了data-id等属性，添加这些属性的代码具体在那方便说一下吗？我暂时没有找到

**Comment by ccloli** [comment]
请确保新增的组件正确透传剩余的 props 到外层的 DOM 节点上，也可以手动将 props 里的 `data-dnd` 与 `data-id` 传入 DOM 节点：

```jsx
const Foo = ({ value }) => (
    <div>{value}</div>
); // ×

const Bar = ({ value, ...rest }) => (
    <div {...rest}>{value}</div>
); // √

const Baz = ({
    value, [SLOT.dnd]: dataDnd, [SLOT.id]: dataId, // see packages/helpers/src/helpers/constants.ts
}) => (
    <div data-dnd={dataDnd} data-id={dataId}>{value}</div>
); // √ （建议仅在 designerConfig.render 内使用）
```

如果没有实体 DOM 节点，可以考虑在使用 `defineComponent()` 时，指定 `designerConfig.render` 在设计器模式下添加一个实体 HTML 节点包裹，或者指定 `designerConfig.hasWrapper` 为 `true` 来自动创建一个实体节点。

具体可参考 https://github.com/NetEase/tango-boot/blob/main/packages/boot/src/defineComponent.tsx 以及 https://github.com/NetEase/tango-components 示例组件库的实现。

**Comment by 1303106965** [comment]
谢谢大佬🎉
