### ISSUE TITLE
设计的页面代码导出后无法通过npm start运行

### ISSUE THREAD

**Issue by 1490113799** [NetEase/tango#219]
今天想验证一下设计页面的源代码是否可以本地运行，导出代码后发现package.json中没有相应的运行命令，请问应该如何运行设计页面的源代码
设计页面截图
![image](https://github.com/user-attachments/assets/237ff11e-4620-43bf-b282-0dba1c06506e)

导出后的页面源代码截图，没有运行代码工程的命令
![image](https://github.com/user-attachments/assets/6e314fd0-96a6-40db-8d52-ae7aa975d8cb)

**Comment by wwsun** [comment]
目前提供的示例项目仅供参考，可以使用 webpack 自行构建
