### ISSUE TITLE
使用 @music163/tango-boot 的runApp包，集成到本地react项目时报undefined

### ISSUE THREAD

**Issue by yiRain123** [NetEase/tango#224]
![image](https://github.com/user-attachments/assets/7d93cbbe-40f3-42c4-b324-4a92cb093114)
![image](https://github.com/user-attachments/assets/329e139a-035a-4ba6-82ff-453f65a263cb)

**Comment by wwsun** [comment]
参考下 demo 项目呢 https://github.com/NetEase/tango-boot/tree/main/examples/basic-example
