### ISSUE TITLE
源码导出到存量工程，有什么集成方案吗

### ISSUE THREAD

**Issue by yiRain123** [NetEase/tango#225]
源码集成到本地项目，目前发现几个问题，
1、源码的主文件index.js，模型和变量视图、接口等分散在不同的项目，且与平时开发习惯有较大出入
2、目前源码导出后，需要在本地工程的启动入口配置runApp，对存量项目侵入较大
请问咱们团队有没有这方面的方面或建议？

**Comment by wwsun** [comment]
当前版本是以网易内部的微前端应用规范为主。后续版本会考虑解藕这部分规范的依赖。
