### ISSUE TITLE
AST: 是否支持随意改动，包括结构改动、使用自定义组件、使用社区开源(Antd、Element) 等

### ISSUE THREAD

**Issue by yejimeiming** [NetEase/tango#25]
**首先非常感谢 tango 团队的付出！我有几个问题还没想明白，所以开个 issues 问一下**

**问题1**：看起来是有物料约束的，虽然说摆脱了 JSON Schema 的约束

<img width="470" alt="image" src="https://github.com/NetEase/tango/assets/135394392/04c450ef-1779-4e98-8859-2dbd8bfaeef3">

---

**问题2**：生成代码看起来是有一定的结构约束的

<img width="470" alt="image" src="https://github.com/NetEase/tango/assets/135394392/6c2aec88-32cf-4a27-8917-65fcaf5cc4c1">

---

**问题3**：是否支持 `.vue` template，是否可以在与已有的业务页面代码兼容？还是说必须符合 **Tango** 提供的页面结构。

**Comment by wwsun** [comment]
q1: 物料协议描述的是组件的 api 和组件包，说明组件包如何使用，组件 api 有哪些
q2: 引擎默认按照标准结构生成 react 代码，具体的生成逻辑也可以通过自定义 setter 进行自定义
q3: 目前只适配了 react 的 ast 语法，没有适配 vue，没有适配 typescript

**Comment by yejimeiming** [comment]
感谢你的回答 👍
这给我对基于 AST 的 LowCode 的实现方案更清晰了。
