### ISSUE TITLE
是否支持多语言 i18n ?

### ISSUE THREAD

**Issue by zjfresh** [NetEase/tango#28]
看了下现在各大低代码平台，好像对于这一块的支持度比较差

**Comment by wwsun** [comment]
具体是哪方面的多语言？ 平台的，还是 产物应用的？

**Comment by zjfresh** [comment]
产物应用，组件 component 中有文案内容的，支持设置多语言文本

**Comment by wwsun** [comment]
这部分目前不在开源范围，可以采用社区典型的多语言方案。例如 https://github.com/i18next/react-i18next/
