### ISSUE TITLE
本地已有沙箱，如何接入？

### ISSUE THREAD

**Issue by fy9311** [NetEase/tango#29]
我本地已经启动了一个sandpack沙箱，如何用它来替换sandbox？
我改写了bundlerURL，但问题是没法打通整个拖拽及事件系统

**Comment by wwsun** [comment]
跨域了吧，需要确保在同域下

**Comment by fy9311** [comment]
> 跨域了吧，需要确保在同域下

感谢回复，确实是在同一域名下，但是我看playground里，Sandbox那个组件需要接收到message回调来初始化基础组件和对应的property，我这边能渲染出来我的沙箱，但是里面的初始化操作没法进行，要是能有个自有沙箱接入指引就好了

**Comment by wwsun** [comment]
> > 跨域了吧，需要确保在同域下
> 
> 感谢回复，确实是在同一域名下，但是我看playground里，Sandbox那个组件需要接收到message回调来初始化基础组件和对应的property，我这边能渲染出来我的沙箱，但是里面的初始化操作没法进行，要是能有个自有沙箱接入指引就好了

@ccloli 可以完善下沙箱的部署和接入文档

**Comment by ccloli** [comment]
> 我本地已经启动了一个sandpack沙箱，如何用它来替换sandbox？

辛苦确认下本地的 sandpack 沙箱是否是从 https://github.com/NetEase/codesandbox-client 克隆下来的版本，并且是按照文档中提到的使用 Caddy 启动的，理论上该仓库的 Caddyfile 已经包含了允许跨域交互的响应头。

如果 codesandbox 不是通过 Caddy 启动的（如 nginx 等），请确认沙箱与 playground 的请求返回的 HTTP 响应头均包含 `Origin-Agent-Cluster: ?0` 。可以通过查看浏览器开发者工具里的网络请求，确认沙箱的 http 响应头是否有这一条。

如果已确认上述问题无误，辛苦提供下浏览器开发者工具中 console 的错误输出。

***

如果你对为什么会有上述要求感兴趣，可以参考下面的解释：

由于 codesandbox 构建的产物的一些限制，其必须从一个域名的根路径下加载，否则一些静态资源或 web worker 会无法正常加载。而这也意味着 playground 的 origin 和 sandbox 会不一致（即便是域名一致，也是在不同的端口上启动的），出现跨域访问问题。

为了解决跨域交互的问题，我们采用了经典解决方案，通过修改 `document.domain` 让设计器与沙箱落在相同的二级域名下，来实现 iframe 的跨域交互。但是 Chrome 在 115 对上述逻辑做了默认限制，因此需要追加 `Origin-Agent-Cluster: ?0` 这一响应头来绕过 Chrome 的限制。

**Comment by fy9311** [comment]
> > 我本地已经启动了一个sandpack沙箱，如何用它来替换sandbox？
> 
> 辛苦确认下本地的 sandpack 沙箱是否是从 https://github.com/NetEase/codesandbox-client 克隆下来的版本，并且是按照文档中提到的使用 Caddy 启动的，理论上该仓库的 Caddyfile 已经包含了允许跨域交互的响应头。
> 
> 如果 codesandbox 不是通过 Caddy 启动的（如 nginx 等），请确认沙箱与 playground 的请求返回的 HTTP 响应头均包含 `Origin-Agent-Cluster: ?0` 。可以通过查看浏览器开发者工具里的网络请求，确认沙箱的 http 响应头是否有这一条。
> 
> 如果已确认上述问题无误，辛苦提供下浏览器开发者工具中 console 的错误输出。
> 
> 如果你对为什么会有上述要求感兴趣，可以参考下面的解释：
> 
> 由于 codesandbox 构建的产物的一些限制，其必须从一个域名的根路径下加载，否则一些静态资源或 web worker 会无法正常加载。而这也意味着 playground 的 origin 和 sandbox 会不一致（即便是域名一致，也是在不同的端口上启动的），出现跨域访问问题。
> 
> 为了解决跨域交互的问题，我们采用了经典解决方案，通过修改 `document.domain` 让设计器与沙箱落在相同的二级域名下，来实现 iframe 的跨域交互。但是 Chrome 在 115 对上述逻辑做了默认限制，因此需要追加 `Origin-Agent-Cluster: ?0` 这一响应头来绕过 Chrome 的限制。

感谢回复！
本地的sanpack是我自己安装sandpack-react启动的，我把它打包之后将dist改为www，然后通过caddy启动，请求回来localhost的响应里也包含了Origin-Agent-Cluster: ?0，目前的结果是：
1.我的sanpack demo无法正常展示出来，因为这段代码里的loading无法被置为false
![image](https://github.com/NetEase/tango/assets/36318519/1f596fce-1f0b-4cad-bfe7-ca254f2697e3)
2.我注释掉loading后，我的demo展示了出来，但是没法触发onMessage的回调，导致组件列表为空且一直loading中
![image](https://github.com/NetEase/tango/assets/36318519/2d7674b7-c131-43d9-b3b3-23801c2e101b)
![image](https://github.com/NetEase/tango/assets/36318519/5f32c657-adb8-49a8-a1d3-17dfb1410e4f)

 我目前的困惑是，我自己提供的sandpack需要做哪些其他的处理才能够触发上述的回调

**Comment by ccloli** [comment]
> 本地的sanpack是我自己安装sandpack-react启动的

我们不推荐直接使用官方版本的沙箱，因为我们 fork 的版本对 sandpack 的逻辑做了一些修改，例如上面提到的 `document.domain` 的调整，以及将配置文件拆出为 `sandbox.config.json` 等。这些修改可能无法与官方的版本兼容，并且不使用我们提供的 fork 版本的沙箱是不受支持的，you have been warned.

> 我目前的困惑是，我自己提供的sandpack需要做哪些其他的处理才能够触发上述的回调

如果你无论如何都希望使用自己的沙箱（例如本地已经对沙箱做了不兼容的修改），那么可以尝试为沙箱注入一段同步设置 `document.domain` 为二级域名（Second-level Domain）的代码，以与 playground 保持一致：

```js
document.domain = window.location.hostname.split('.').slice(-2).join('.');
```

保证在沙箱 load 完成前执行上述代码后，设计器即可与沙箱内部通信，并能从沙箱内部获取到组件物料的元数据信息。

此外我们对沙箱的配置文件加入了一些扩展支持，具体修改的内容请查看之前链接的 fork 版本的 codesandbox 中 README 的 Changes 一节。因此只做上述修改有可能仍然无法让沙箱运行到最佳状态，或者有可能无法正常运行。如果你仍然希望使用自己的沙箱，请尝试 cherry-pick 上述 fork 版本的 [相关修改](https://github.com/codesandbox/codesandbox-client/compare/master...NetEase:codesandbox-client:master) 并重新构建与编译。

再次提醒，不使用我们提供的修改版本的沙箱是非预期的且不受我们支持的，我们也不能保证上述修改后你本地的沙箱能与设计器完全兼容。

**Comment by ccloli** [comment]
此外，除了上面提到的修改外，请确认 playground 与 sandpack 均是在相同的二级域名下（例如均为 *.netease.com 的子域名）。例如上述截图中，`127.0.0.1` 与 `localhost` 显然不是同域，请尝试都改为 `localhost`。否则 `document.domain` 的设置不会正常工作，且最终仍为跨域调用。

**Comment by fy9311** [comment]
> 此外，除了上面提到的修改外，请确认 playground 与 sandpack 均是在相同的二级域名下（例如均为 *.netease.com 的子域名）。例如上述截图中，`127.0.0.1` 与 `localhost` 显然不是同域，请尝试都改为 `localhost`。否则 `document.domain` 的设置不会正常工作，且最终仍为跨域调用。

OK,感谢回复，那我还是返回去使用已提供的沙箱吧，谢谢啦
