### ISSUE TITLE
震惊和我想做的低码出奇的一致

### ISSUE THREAD

**Issue by hlerenow** [NetEase/tango#3]
和我想做的低码出奇的一致，做前端的增强开发工具，并且可以导出源码，给其他系统做集成。
希望越做越好。

PS: chameleon 低码引擎  https://github.com/hlerenow/chameleon

**Comment by wwsun** [comment]
👍 很不错的项目。tango 目前已经在网易云音乐内网环境使用了 1 年办了，本次开源版本会将其中的核心低代码引擎部分开源，后续我们会进一步的逐步完善，希望能够与社区的同学共同交流与学习。
