### ISSUE TITLE
设计区域，组件拖拽调整位置不太好操作

### ISSUE THREAD

**Issue by shelwinjue** [NetEase/tango#31]
比如，想将下方组件拖到上方组件的前面无法做到，只能拖动上方组件到下方组件的下面
![image](https://github.com/NetEase/tango/assets/6322676/e38f857b-75a8-40a7-b47f-e1826bc56617)

图中显示，只能将input组件拖到button组件的后面，无法拖到button的前面

**Comment by wwsun** [comment]
目前社区版直接使用了原生的 antd 组件，没有做额外的拖拽规则适配，相关的体验优化我们在 RC 版本发布后进行完善
