### ISSUE TITLE
codesandbox-client协议是GPLV3，如何进行商业化？

### ISSUE THREAD

**Issue by Plortinus** [NetEase/tango#34]
这个框架用的codesandbox-client是GPLV3的，那这个框架也得是GPLV3的，如何进行商业化？

**Comment by ccloli** [comment]
Tango 主要使用的是 codesandbox 的 Sandpack 能力，而 Sandpack 部分使用的协议是 Apache 2.0

> CodeSandbox is licensed under GPLv3, except for `packages/common` and `packages/sandpack-core` and `packages/app/src/sandbox`,
> which are licensed under the Apache License, Version 2.0.

我们修改 Sandpack 的代码可以在 https://github.com/NetEase/codesandbox-client 找到，且适配修改的部分均在上述路径下

**Comment by wwsun** [comment]
这部分请遵守 codesandbox 的开源协议
