### ISSUE TITLE
这个项目的使用流程是什么? 

### ISSUE THREAD

**Issue by vaynevayne** [NetEase/tango#38]
拖拉拽得到一份react 项目源码 ?  然后 push 到 github, 再通过 ci  cd 发布, 再通过 iframe 嵌入到现在项目的某一块吗?

**Comment by wwsun** [comment]
目前开源的仅仅是低代码引擎部分，提供核心的搭建能力。其他涉及到的低代码平台逻辑，发布逻辑，部署逻辑均不在本次的开源范围哦。

可以关注我们后续的发布计划和开源规划。
