### ISSUE TITLE
文档演示应用拖拽异常

### ISSUE THREAD

**Issue by Harhao** [NetEase/tango#46]
无法拖拽，无反应

**Comment by ccloli** [comment]
请问 issue 里提到的演示应用是示例站点 https://tango-demo.musicfe.com/ 还是本地启动 playground 呢？如果是示例网站的话，理论上沙箱和 demo 是同域的，应该是能正常交互的，辛苦提供下浏览器控制台的错误信息

如果是本地启动 playground，请确认已严格按照 [文档](https://netease.github.io/tango/docs/designer/quick-start) 中的流程初始化，尤其是「启动本地沙箱」部分。由于本地调试本质上是需要跨域操作的，在 Chrome 上需要特定的 HTTP 响应头，因此需要使用特定的 Web 服务器配置才能正常运行。如果使用了其他 HTTP 服务器，请确认沙箱的 HTTP 请求包含 `Origin-Agent-Cluster: ?0` 这一响应头

**Comment by wwsun** [comment]
目前示例应用的组件库是使用 antd 简单包装的。组件部分我们目前正在逐步的完善中，有一些功能还没完全并到社区版本中，我们会在近期进行完善。

**Comment by wwsun** [comment]
@ccloli 后续我们可以提供一个带 Node Server 的标准示例应用

**Comment by FKLam** [comment]
本地启动的playground的，没有保存按钮，只有发布按钮 @ccloli ，你提到的文档，点击入去是找不到的，麻烦重新提供新的文档。谢谢

**Comment by ccloli** [comment]
> 本地启动的playground的，没有保存按钮，只有发布按钮 @ccloli ，你提到的文档，点击入去是找不到的，麻烦重新提供新的文档。谢谢

上面的使用文档已经迁移至 https://netease.github.io/tango-site/docs/designer/quick-start/ ，原来的路由目前已经改为组件的 API 文档。

目前 Tango 开源的部分是核心的搭建引擎，playground 主要是预览 Tango 的搭建能力，所以周边功能还没有补充到示例应用中，后续我们会完善示例应用的功能。

如果你需要获取引擎搭建的源码，可以在 playground 中绑定发布按钮的 onClick 事件，通过调用 `workspace.listFiles()` 或直接访问 `workspace.files` 获取引擎内部的文件源码。
