### ISSUE TITLE
页面结构下的节点id每次editor save都会自增

### ISSUE THREAD

**Issue by xiong-john** [NetEase/tango#47]
<img width="378" alt="image" src="https://github.com/NetEase/tango/assets/6100541/a955a043-8768-4408-aa9f-471182447f82">

定位到了代码位置，但是找不到原因。

<img width="915" alt="image" src="https://github.com/NetEase/tango/assets/6100541/14855225-8484-494b-8660-0cefb68fab35">
这个函数在editor save时会执行两次，第二次为什么会执行没debug出来；
<img width="987" alt="image" src="https://github.com/NetEase/tango/assets/6100541/c5379c24-14e7-4c66-9706-4ea47067a390">

**Comment by wwsun** [comment]
这个 ID 目前是动态的，只是引擎内部进行节点跟踪用的，所以在页面更新的时候 ID 可能会变化，这并不会影响到搭建逻辑或设计器的功能可用性

**Comment by wwsun** [comment]
已支持静态 ID，可以在属性面板制定组件的 ID
