### ISSUE TITLE
低代码平台提效的点在哪里

### ISSUE THREAD

**Issue by ratelgogo** [NetEase/tango#60]
首先感谢网易云团队将低代码平台核心代码开源，其次我想问下，低代码平台一般都是给开发同学使用的，这种方式和传统的直接写代码的方式提效的点在哪，方便透露下内部使用了之后降本增效的数据吗？感谢🙏

**Comment by wwsun** [comment]
这方面的数据可以关注 《网易云音乐技术团队》公众号分享，我们会有持续的内部进展分享。

tango 的初衷是面向传统的源码场景提供渐进式的低码方案，提供在线（源码/可视化）开发能力
