### ISSUE TITLE
 AI Copilot 功能什么时候上线?

### ISSUE THREAD

**Issue by balance-joe** [NetEase/tango#64]
我是看这篇文章关注到的  《云音乐低代码 + ChatGPT 实践方案与思考》[https://mp.weixin.qq.com/s/jaIiVI636uJBOOKsXuHCpw](url)
感觉本项目非常有意思,于是下载代码运行后发现本地运行的版本并没有此功能,组件似乎也没有readme中的功能多
请问准备什么时候上线 AI Copilot功能和开放更多组件呢

**Comment by wwsun** [comment]
1. 组件部分的功能因为近期事项比较多有些延期，后面我会将内网组件库和外网开源版本进行统一，计划在 12 月 ~ 明年1月期间进行。
2. AI Copilot 的部分因为有一些功能依赖内网服务，暂时还未做好开源准备，可以关注我《云音乐技术团队》公众号，计划在明年会开始推进这部分能力的开源。
