### ISSUE TITLE
沙箱运行起来了 但是报错

### ISSUE THREAD

**Issue by wangminqinag** [NetEase/tango#80]
首先感谢网易音乐云团队的付出。
![image](https://github.com/NetEase/tango/assets/26113336/d9b9618d-21aa-4361-a008-7223d8db1740)
1、看着像是环境变量的问题，请大佬指正
2、正式版咱们准备什么时候发行呢
3、项目中使用的是vue3 + element-plus 的二次封装， 怎么把项目修改成 vue3 的项目， 大佬能否说一下方案，或者应该注意的地方，愿意为社区贡献一份薄利

**Comment by wangminqinag** [comment]
已经解决了，单独访问 沙箱 8843 端口 不能打开必须 访问 tango 起的 https://local.netease.com:8001/ 服务， 希望能帮助到别人

**Comment by wangminqinag** [comment]
咱们封装的  codesandbox-client  支持 vue的 ast 树吗

**Comment by wangminqinag** [comment]
<img width="252" alt="image" src="https://github.com/NetEase/tango/assets/26113336/593b8eca-9645-4369-bfd7-cf1af6207d41">
这些基础组件是从哪来的啊 没找到menuData 数据哪来的 一直没找到， 是沙箱里的吗， 沙箱里也没找到

**Comment by wangminqinag** [comment]
ast 树是怎么传递到 沙盒当中的是同个变量吗

**Comment by ccloli** [comment]
> 咱们封装的 codesandbox-client 支持 vue的 ast 树吗

codesandbox-client 运行的是源码，其本身是有 vue-cli 的模板的，所以理论上可以运行 Vue，我们也没有修改过 vue-cli 的 preset

不过估计你可能更想知道 Tango 是否支持，这里需要说明一下，Tango 目前只适配了 React 的场景，还未适配 Vue，后续可以考虑通过社区共建的形式支持，参见 #2

> 这些基础组件是从哪来的啊 没找到menuData 数据哪来的 一直没找到， 是沙箱里的吗， 沙箱里也没找到

基础组件是在 `tango.config.json` 里定义的，基础组件库自身会提供组件库的 menuData 与 prototypes 定义供 Tango 引擎消费

至于如何获取，可参考 `apps/playground` 的源码。示例的组件库是通过 umd 加载的，所以挂在全局变量上，因此可以从沙箱 iframe 的全局变量上获取到这些属性（也可以采用其它方式，例如在初始化引擎后，通过代码主动注册 menuData 与 prototypes）

> ast 树是怎么传递到 沙盒当中的是同个变量吗

AST 未传递到沙箱中，沙箱运行的是项目的源代码。设计模式下与沙箱交互时，沙箱会触发事件传递当前操作的节点。引擎根据节点信息到 AST 树上查找节点，然后高亮节点并展示组件的配置信息。节点修改配置后映射为 AST 上的修改，AST 还原为源码，再将更新后的源码传入沙箱渲染

**Comment by wangminqinag** [comment]
@ccloli 首先感谢大佬的回复
1、咱们的源码我看了一部分， 咱们所有的 issues 我也都看了一遍
2、至于menuData从哪生成的不是关键， 但是在整个项目中搜索 “数字输入框” 都搜索不到， 那就是有可能是接口？
3、我是知道咱们 tango 是不支持 vue 的， 但是你们这种思路我之前有想过 奈何做不到，看到咱们项目之后有点不明觉厉，
4、如果像大佬说的 codesandbox-client 是可以运行vue的， 我理解的不知道对不对， 如果修改成vue3 的逻辑， 是不是生成vue3源代码和生成vue3 的 ast 树 是关键，  如果修改 tango.config.json 修改成 vue3 的依赖 和生成 AST树 这样能运行说明方案是可行的

**Comment by ccloli** [comment]
> 2、至于menuData从哪生成的不是关键， 但是在整个项目中搜索 “数字输入框” 都搜索不到， 那就是有可能是接口？

如果你指的是左侧组件面板的定义在哪，示例的 menuData 和 prototypes 是定义在组件库中的，具体可移步 https://github.com/NetEase/tango-components 。组件是 UMD 加载的，所以只需通过 `iframe.contenWindow.TangoAntd.menuData` 与 `iframe.contenWindow.TangoAntd.prototypes` 即可获取

如果你指的是右侧组件配置的输入框，这些是在 prototypes 里定义的，例如定义一个参数为数值，需要在该参数上指定 `setter: 'numberSetter'`，具体可参考上述项目中的 prototypes 配置



> 4、如果像大佬说的 codesandbox-client 是可以运行vue的， 我理解的不知道对不对， 如果修改成vue3 的逻辑， 是不是生成vue3源代码和生成vue3 的 ast 树 是关键， 如果修改 tango.config.json 修改成 vue3 的依赖 和生成 AST树 这样能运行说明方案是可行的

理论上来说是的，codesandbox（或者具体一点，它的沙箱实现 Sandpack） 自身是能运行 Vue 的，你可以在 CodeSandbox 的官网上运行

核心是引擎侧需要能将 Vue 的源代转换成 AST，给组件附加上唯一 id，再转换回源代码并传入沙箱，从而让沙箱能感知当前选中的节点。除此之外，引擎侧应该只适配了 React，对 Vue 可能需要再做些适配工作

另外上面也提到，组件库需要封装 menuData 与 prototypes，除此之外，还需要在组件库层面封装针对设计模式响应拖拽的能力，因此大概率是不能直接使用原始的组件库的，需要参考上面提到的组件库的仓库，对组件库做二次封装

**Comment by wangminqinag** [comment]
@ccloli  
1、大神 我是想着 修改一下 mock files.ts 文件 修改成vue的
2、修改一下workspace.ts 的 this.files 的返回值， 例如：html 文件
![image](https://github.com/NetEase/tango/assets/26113336/24bfeda8-4f76-493e-a48f-a7363bef794b)
![image](https://github.com/NetEase/tango/assets/26113336/66d50e89-ee74-402d-a345-0814bfe808e5)
![image](https://github.com/NetEase/tango/assets/26113336/bde93084-a614-4385-8efa-36c77e171593)
![image](https://github.com/NetEase/tango/assets/26113336/9b919fc7-ffc1-44d1-ac65-cfeb939ddecd)
![image](https://github.com/NetEase/tango/assets/26113336/7595a759-656d-4de7-a07b-723b54068391)
我在 workspace.ts 中手动修改 ast 属性 为什么不行呢， ast 是我在网上  https://template-explorer.vuejs.org/#eyJzcmMiOiJcbmltcG9ydCB7IGNyZWF0ZUFwcCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHJvdXRlciBmcm9tICcuL3JvdXRlcidcblxuaW1wb3J0ICcuL2Fzc2V0cy9tYWluLmNzcydcblxuY29uc3QgYXBwID0gY3JlYXRlQXBwKEFwcClcblxuYXBwLnVzZShyb3V0ZXIpXG5cbmFwcC5tb3VudCgnI2FwcCcpIiwib3B0aW9ucyI6e319 转的， 大神我需要注意哪些呢

还有 files 的type 有什么作用吗， 我看大神是自定义的

**Comment by ccloli** [comment]
首先还是需要再说明一下，Tango 只支持 React 的页面搭建，不支持 Vue 的解析与搭建，上述讨论只是理论上可行而已，引擎层面目前对 Vue 没有做任何支持


> 我是想着 修改一下 mock files.ts 文件 修改成vue的

CodeSandbox 在初始化时需要指定模板，而 [代码](https://github.com/NetEase/tango/blob/main/packages/sandbox/src/code-sandbox/index.tsx#L24) 里已经指定了模板为 `create-react-app`。因此除非修改模板，否则是无法转译与渲染 Vue 的


> 我在 workspace.ts 中手动修改 ast 属性 为什么不行呢

项目内使用的 AST 是基于 ESTree 的，生成和转换是基于 Babel 的，这一点在 [文档](https://netease.github.io/tango/docs/intro#%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86) 中有提到过。所以，其他的 AST 规则不一定能够适用，Tango 也不一定能够直接使用 Vue 的 AST


综上，如果需要让 Tango 支持 Vue 还是需要不少的工作的，包括支持 AST 的解析、节点的映射、AST 的修改、代码的还原、沙箱渲染的适配等，不是简单地传入代码就能直接实现的


至于与引擎相关的内容，建议还是咨询下 @wwsun

**Comment by wangminqinag** [comment]
@ccloli  还是要打扰你一下
1、
![image](https://github.com/NetEase/tango/assets/26113336/47cbf803-b8e7-4ede-9197-f7ee0c5c391f)
![image](https://github.com/NetEase/tango/assets/26113336/05c763f2-7486-478b-ace8-f54e30cba16a)
为什么 在 manager.ts 中要执行 这两个方法呢，因为我觉得在 iframe-protocol.ts 中的 eventListener 这个方法已经循环之行了

2、在 iframe-protocol.ts  通过 window.addEventListener('message', this.eventListener); 执行这个方法， 是因为 在这个类中 register， dispatch 方法postMessage 出发的吗
![image](https://github.com/NetEase/tango/assets/26113336/82640c54-3ec4-40d5-9dde-667ea95fedc6)
我觉得这个方法是不是发送给 沙箱的呢
3、
![image](https://github.com/NetEase/tango/assets/26113336/34aec901-2e2a-4b1d-b1aa-fb4757761451)
这里都已经删除 delete this.globalListeners[listenerId] 了
在eventListener 循环执行还可以吗，
manager.ts 和 iframe-protocol.ts 的逻辑不是很清楚，能否解释一下这两个文件呢

**Comment by wangminqinag** [comment]
@ccloli 你好， 我发送了 gmail 邮件， 能否回复一下

**Comment by wangminqinag** [comment]
@ccloli 
1、CodeSandbox 在初始化时需要指定模板，而 [代码](https://github.com/NetEase/tango/blob/main/packages/sandbox/src/code-sandbox/index.tsx#L24) 里已经指定了模板为 create-react-app。因此除非修改模板，否则是无法转译与渲染 Vue 的

这个是上述中您的回答，没太看明白，初始化模版在那个地方， 代码 template: 'create-react-app', 删除一样能渲染成功，说明没有初始化入口， 怎么能换成 vue 的呢， 咱们的项目的前后逻辑我基本上都已经看懂了， 准备下周想搭建vue 的demo， 能否提供一点思路

2、上述中想让社区搭建vue 的版本， 可以通过什么渠道参与进来呢

**Comment by wangminqinag** [comment]
<img width="725" alt="image" src="https://github.com/NetEase/tango/assets/26113336/0f70fd9c-8d4d-424d-b3e8-72fcccb251fb">
确实和模版没有太大的关联

**Comment by ccloli** [comment]
> 这个是上述中您的回答，没太看明白，初始化模版在那个地方， 代码 template: 'create-react-app', 删除一样能渲染成功，说明没有初始化入口， 怎么能换成 vue 的呢

`vue-cli` 的 preset 有注册 `@vue/babel-preset-env` 的逻辑，具体参见 CodeSandbox 的源码：
https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/sandbox/eval/presets/vue-cli/index.ts

如果删除了 `template`，CodeSandbox 有根据项目的文件结构与 `package.json` 来推断 Preset 的能力，此时应该是自动推断使用了 `vue-cli` 的 template 对应的 Preset





> 上述中想让社区搭建vue 的版本， 可以通过什么渠道参与进来呢

可以考虑给项目直接提供 PR，不过由于之前提到的原因，Vue 应该不是我们的首要事项。如果感兴趣的话，可以和 @wwsun 具体聊聊

**Comment by wangminqinag** [comment]
@ccloli  好的 
1、确实用import App from './App.vue' 是不行的， 我本以为是没有转成ast 树的原因
明白确实目前vue 不是重点， 因为我们封装了很多vue 的业务组件， 所以没办法用 react,
2、大佬能否给一个 import App from './App.vue' 可以运行的模版呢， 因为看 tango 已经费了很大的劲， 没办法在看codesanbox 的代码了，现在就差这一块， 其他的逻辑基本上已经梳理清楚
3、在看咱们源码的过程中 发现整个逻辑和 咱们的组件库耦合非常严重， 别的组件库就没办法用了，不过这个也不是重点

**Comment by ccloli** [comment]
> 大佬能否给一个 import App from './App.vue' 可以运行的模版呢

其实应该还是没有指定 template 的问题，我本地基于 playground 改了下是能正常跑起来的。当然只是沙箱能跑起来而已，因为这部分不是 Tango 的能力，而是 CodeSandbox 的能力，所以 playground 中 Tango 的能力都是失效的

![](https://p6.music.126.net/obj/wo3DlcOGw6DClTvDisK1/32582790549/c092/4ee7/cd5c/eea0725e4f3ef3de8ba28d118cdc24f1.png)

首先你需要在 `<Sandbox>` 组件上指定 `template="vue-cli"`：
![](https://p6.music.126.net/obj/wo3DlcOGw6DClTvDisK1/32582835215/7208/28ec/1491/e245e56ded46c6f3ea7f8d4433bbd47b.png)

然后将 `mock-files.ts` 里的 `sampleFiles` 按照格式，替换为上述项目中的文件，例如你可以直接用这个 json 文件：
https://d2.music.126.net/dmusic/obj/w5zCg8OAw6HDjzjDgMK_/32582927018/0364/02a5/daab/4d50e9dfb884693c45e7455e724f00a7.json?download=vue.json

理论上这样就能正常渲染 Vue 的项目了，不过还是强调下，这是 CodeSandbox 自身的能力，你甚至可以直接用 CodeSandbox 提供的 Sandpack 组件来实现：
https://sandpack.codesandbox.io/docs/getting-started/usage



> 在看咱们源码的过程中 发现整个逻辑和 咱们的组件库耦合非常严重， 别的组件库就没办法用了

是的，所以是需要对组件库做之前提到的二次封装的，让组件库符合 Tango 的基础物料协议



> 咱们的正式版本准备什么时候发呢， 因为还没又看到怎么触发弹框的逻辑

正式版本应该会在近期发布

是指点击按钮触发弹窗或者命令式展示弹窗的逻辑？弹窗这部分的功能和内部封装的组件库绑定比较深，重度依赖组件库二次封装的能力，所以这块是没有开源的

**Comment by wangminqinag** [comment]
@ccloli  大佬请教一下，这个属性是从哪里赋值的
![image](https://github.com/NetEase/tango/assets/26113336/cc30f43f-a834-4d37-992d-b70f683a9620)

**Comment by wangminqinag** [comment]
@ccloli  大佬， 能否帮忙解释一个问题呢， 在iframe-protocol.ts 中 dispatch 的 modules 里的app.vue 文件已经更新了，应该也执行了 postMessage 通信， 为什么 iframe 的元素没有更新呢， 只有拖拽的没有更新， 但是在mock-file 中的元素初次加载没有问题，
如果把 iframe 显示隐藏从新加载就能 更新成最新的， 但是不能每次拖拽都 显示隐藏，图中也有 react 和 vue  message 的对比，能否解释一下大概出现的问题。
![image](https://github.com/NetEase/tango/assets/26113336/182de562-3af1-404a-bc17-e9ce75250b59)

**Comment by wangminqinag** [comment]
@wwsun 大佬有时间帮忙解释一下， 上边通信的问题呗， 卡在这里了
