### ISSUE TITLE
《云音乐低代码 + ChatGPT 实践方案》这部分会考虑加入开源吗？

### ISSUE THREAD

**Issue by zfanswer** [NetEase/tango#81]
https://zhuanlan.zhihu.com/p/634096142
看了这个文章，找到了这个低代码开源项目，发现好像没有GPT那一部分，想问下那一部分会考虑加入开源吗？

**Comment by wwsun** [comment]
涉及一些内部的服务和数据，暂不考虑开源这部分能力。
