### ISSUE TITLE
运行sandbox是否可以用nginx替换Caddy

### ISSUE THREAD

**Issue by arcelan** [NetEase/tango#84]
目前看到以下命令会构建出www的静态资源
```
yarn install
yarn build:deps
yarn build:sandpack
```

Caddy依赖的配置是以下几项
1. https的设置
2. local.netease.com的域名设置
3. Origin-Agent-Cluster ?0 的 header设置

请问如果替换成nginx的话，是否只要满足以上3点就可以了？
是否还依赖Caddy的其他特性？

**Comment by ccloli** [comment]
> 请问如果替换成nginx的话，是否只要满足以上3点就可以了？

可以的，只需要配置好 https 和 `root` 与 `add_header` 即可

**Comment by arcelan** [comment]
> > 请问如果替换成nginx的话，是否只要满足以上3点就可以了？
> 
> 可以的，只需要配置好 https 和 `root` 与 `add_header` 即可

感谢！

**Comment by arcelan** [comment]
附上nginx配置

```
  server {
    listen       443 ssl;
    server_name  local.netease.com;
    ssl_certificate  /etc/nginx/ssl/local.netease.com.pem;
    ssl_certificate_key  /etc/nginx/ssl/local.netease.com-key.pem;
    root  /usr/share/nginx/html/;
    add_header Origin-Agent-Cluster "?0";
  }
```
`/usr/share/nginx/html/` 对应 https://github.com/NetEase/codesandbox-client.git build出来的静态文件
证书文件可以从 https://github.com/NetEase/tango/tree/main/apps/playground 找到
