### ISSUE TITLE
是否可以将sandbox部署在相对路径上

### ISSUE THREAD

**Issue by arcelan** [NetEase/tango#87]
目前sandbox是部署在根目录下，资源也是通过绝对路径加载的，导致部署在相对路径（比如/sandbox/）会失败。
但部署在根目录就需要有一个单独的域名。

去[codesandbox-client](https://github.com/codesandbox/codesandbox-client)那边搜索了一下，也有相应的issue但没有提供好的解决方案，想知道这边有没有比较好的方案可以参考。

**Comment by ccloli** [comment]
在部署开源 demo 的时候，我也试着解决过这个问题。不过……CodeSandbox 内部的构建配置比较多，不是很好改，改到最后发现一些 web worker 的资源没法指到相对路径。所以开源版本的 demo 的解决方案是，将沙箱部署在根路径下，然后将设计器部署在 
`/designer` 子路径下

我们内部是将沙箱单独部署在一个域名下的，只要沙箱指定了文档中提到的 HTTP Header，跨域访问就不会有问题

**Comment by arcelan** [comment]
>所以开源版本的 demo 的解决方案是，将沙箱部署在根路径下，然后将设计器部署在
/designer 子路径下

好的，目前我也是按照这个方法来部署的
