### ISSUE TITLE
Tango Playground演示站点 https://s5.music.126.net/static_public/* 请求资源404 

### ISSUE THREAD

**Issue by northpbear** [NetEase/tango#92]
![image](https://github.com/NetEase/tango/assets/12377911/5da72027-0137-4e05-9119-793b9e8df069)

**Comment by northpbear** [comment]
看了一下是react-monaco-editor-lite这个包里面请求的资源，’https://s5.music.126.net/static_public/6194df158463e8444a55b9d8_6194df158463e8444a55b9da/‘路径是在webpack配置里写死的，是不是资源被误删除了？

**Comment by wwsun** [comment]
fixed by https://github.com/NetEase/tango/pull/94
